// <auto-generated />
using APITallerFinal.Model.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APITallerFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200927213148_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APITallerFinal.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("NumeroCasillero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnName("DireccionEntrega")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NombreCliente")
                        .HasColumnType("varchar(50)");

                    b.HasKey("NumeroCasillero");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("APITallerFinal.Models.Entities.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NombreEstado")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEstado");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("APITallerFinal.Models.Entities.Libra", b =>
                {
                    b.Property<int>("IdLibra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FechaFinal")
                        .HasColumnName("FechaFinalizacion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FechaInicio")
                        .HasColumnName("FechaInicio")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ValorLibra")
                        .HasColumnType("int");

                    b.HasKey("IdLibra");

                    b.ToTable("libras");
                });

            modelBuilder.Entity("APITallerFinal.Models.Entities.Paquete", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Casillero")
                        .HasColumnName("CasilleroCliente")
                        .HasColumnType("int");

                    b.Property<int>("Empresa")
                        .HasColumnName("EmpresaTransportadora")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Guia")
                        .IsRequired()
                        .HasColumnName("GuiaColombia")
                        .HasColumnType("varchar(50)");

                    b.Property<float>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Tracking")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Codigo");

                    b.ToTable("paquetes");
                });

            modelBuilder.Entity("APITallerFinal.Models.Entities.TipoMercancia", b =>
                {
                    b.Property<int>("IdTipoMercancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("TipoMercancia")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoMercancia");

                    b.ToTable("tipoMercancias");
                });

            modelBuilder.Entity("APITallerFinal.Models.Entities.Transportadora", b =>
                {
                    b.Property<int>("IdTransportadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NombreTransportadora")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTransportadora");

                    b.ToTable("transportadoras");
                });

            modelBuilder.Entity("APITallerFinal.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnName("Contraseña")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnName("Correo")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
